[build]
    command = "CI = npm run build"
    publish = ".next"
[[headers]]
    for="/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Referrer-Plicy = "strict-origin-when-cross-origin"
        X-Frame-Option = "SAMEORIGIN"
        Strict-Transport-Security = "31536000"
    [[plugings]]
        package = "@netlify/plugin-nextjs"